# Generated by Django 6.0.3 on 2026-03-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado con Observación')], default='APPROVED', max_length=20),
        ),
    ]
