# Generated by Django 6.0.3 on 2026-06-14 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diveactivity_divelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diveactivity',
            name='location',
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='altitude_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='atmospheric_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='dive_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='location_coords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='location_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_medic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='safety_diver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_safety', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='surface_temp_celsius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='visibility_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='water_course_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveactivity',
            name='wind_speed_knots',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='divelog',
            name='decompression_depth_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='divelog',
            name='decompression_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='divelog',
            name='decompression_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divelog',
            name='dive_graph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelog',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='divelog',
            name='residual_nitrogen_post',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='divelog',
            name='residual_nitrogen_pre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='divelog',
            name='suit_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='divelog',
            name='tank_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='divelog',
            name='weight_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='diveactivity',
            name='water_temp_celsius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
