# Generated by Django 6.0.3 on 2026-06-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_diveactivity_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelog',
            name='dive_graph',
            field=models.FileField(blank=True, null=True, upload_to='dive_graphs/'),
        ),
    ]
