# Generated by Django 6.0.3 on 2026-06-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
